version: '3.9'

services:

  mysql:
    image: debezium/example-mysql:1.9
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD:debezium
      MYSQL_USER:mysqluser
      MYSQL_PASSWORD:mysqlpw
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - default

  postgres:
    image: debezium/postgres:12
    container_name: postgres
    healthcheck:
      test: "pg_isready -U postgresuser -d shipment_db"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      POSTGRES_USER:postgresuser
      POSTGRES_PASSWORD:postgrespw
      POSTGRES_DB:shipment_db
      PGPASSWORD:postgrespw
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - default
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  zookeeper:
    image: debezium/zookeeper:1.9
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    expose:
      - 2181
    networks:
      - default

  kafka:
    image: debezium/kafka:1.9
    container_name: kafka
    environment:
      ZOOKEEPER_CONNECT:zookeeper:2181
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    expose:
      - 9092
    networks:
      - default

  connect:
    image: debezium/connect:1.9
    container_name: connect
    environment:
      GROUP_ID:1
      CONFIG_STORAGE_TOPIC:my-connect-configs
      OFFSET_STORAGE_TOPIC:my-connect-offsets
      STATUS_STORAGE_TOPIC=my_connect_statuses
      BOOTSTRAP_SERVERS:kafka:9092
      HOST_NAME:0.0.0.0
    depends_on:
      - kafka
      - mysql
      - postgres
    ports:
      - 8083:8083
    expose:
      - 8083
    networks:
      - default

networks:
  default:
    driver: bridge
